# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pMAtzFsgHs0TiWQQCvnnhzr8c1QV95xl
"""

import requests
from bs4 import BeautifulSoup

url = 'https://www.caak.mn/'
res = requests.get(url)
html_page = res.content
soup = BeautifulSoup(html_page, 'html.parser')
text = soup.find_all(text=True)

output = ''
blacklist = [
	'[document]',
	'noscript',
	'header',
	'html',
	'meta',
	'head', 
	'input',
	'script',
]

for t in text:
	if t.parent.name not in blacklist:
		output += '{} '.format(t)

print(output)
